export type MeUser = {
  id: string;
  email: string | null;
  clerk_user_id: string;
  role: "owner" | "admin" | "member";
  default_rate_cents: number | null;
  is_admin: boolean;
  is_super_admin: boolean;
  easter_egg_enabled: boolean;
};

export type AdminUserRow = {
  id: string;
  email: string | null;
  role: "owner" | "admin" | "member";
  is_admin: boolean;
  easter_egg_enabled: boolean;
  created_at: string;
};

export type AllUsersRow = {
  id: string;
  email: string | null;
  role: "owner" | "admin" | "member";
  is_admin: boolean;
  is_super_admin: boolean;
  org_id: string | null;
  org_name: string | null;
  created_at: string;
};

export type UpdateAdminUserInput = {
  is_admin?: boolean;
  easter_egg_enabled?: boolean;
};

export type Me = {
  user: MeUser | null;
  org: {
    id: string;
    clerk_org_id: string;
    plan: string;
  };
};

export type UpdateMeInput = {
  default_rate_cents?: number | null;
};

export type Client = {
  id: string;
  name: string;
  email: string | null;
  billing_address: string | null;
  notes: string | null;
  default_rate_cents: number | null;
  arAutomationEnabled: boolean | null;
  arApprovalRequired: boolean | null;
  arRemindersEnabled: boolean | null;
  arReminderCadenceDays: number | null;
  created_at: string;
  updated_at: string;
};

export type CreateClientInput = {
  name: string;
  email?: string;
  billing_address?: string;
  notes?: string;
  default_rate_cents?: number | null;
};

export type UpdateClientInput = {
  name?: string;
  email?: string | null;
  billing_address?: string | null;
  notes?: string | null;
  default_rate_cents?: number | null;
  arAutomationEnabled?: boolean | null;
  arApprovalRequired?: boolean | null;
  arRemindersEnabled?: boolean | null;
  arReminderCadenceDays?: number | null;
};

export type TimeEntry = {
  id: string;
  org_id: string;
  client_id: string | null;
  description: string;
  started_at: string;
  ended_at: string;
  duration_minutes: number;
  hourly_rate_cents: number | null;
  created_at: string;
  updated_at: string;
};

export type CreateTimeEntryInput = {
  client_id?: string;
  description: string;
  started_at: string;
  ended_at: string;
  hourly_rate_cents?: number;
};

export type CreateTimeEntryResponse = {
  entry: TimeEntry;
  warnings?: string[];
};

export type DocsEntry = {
  key: string;
  label: string;
  tooltip: string;
  detail: string;
  docSlug: string;
  whatWeMeasure?: string;
  thresholds?: { label: string; range: string; meaning: string }[];
  commonMisunderstanding?: string;
};

export type DocsCategory = {
  key: string;
  title: string;
  description?: string;
  entries: DocsEntry[];
};

export type DocsRegistry = {
  categories: DocsCategory[];
};

export type OAuthAuthorizeResponse = {
  url: string;
};

export type Platform = {
  id: string;
  type: string;
  external_account_id: string;
  created_at: string;
  updated_at: string;
};

export type InvoiceStatus = "draft" | "open" | "paid" | "void";

export interface Invoice {
  id: string;
  orgId: string;
  clientId: string;
  number: string | null;
  status: InvoiceStatus;
  issueDate: string | null;
  dueDate: string | null;
  subtotalCents: number;
  totalCents: number;
  notes: string | null;
  stripePaymentIntentId: string | null;
  stripeClientSecret: string | null;
  paymentToken: string | null;
  paidAt: string | null;
  autoGeneratedAt: string | null;
  remindersSentCount: number;
  lastReminderSentAt: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface InvoiceLineItem {
  id: string;
  invoiceId: string;
  timeEntryId: string | null;
  description: string;
  quantityHours: number;
  rateCents: number;
  amountCents: number;
  createdAt: string;
}

export interface InvoiceWithItems extends Invoice {
  lineItems: InvoiceLineItem[];
  client: { id: string; name: string; email: string | null };
  stripePublishableKey?: string;
  connectedAccountId?: string;
  paymentUrl?: string;
  paymentUnavailableReason?: "seed_requires_test_mode";
}

export interface SendInvoiceResponse {
  data: Invoice & { warnings?: string[] };
}

export interface PublicInvoicePayment {
  invoice: {
    id: string;
    number: string;
    totalCents: number;
    currency: "usd";
    status: InvoiceStatus;
    orgName: string;
    clientName: string;
  };
  stripeClientSecret: string;
  stripePublishableKey: string;
  connectedAccountId: string;
}

export interface CreateInvoiceInput {
  clientId: string;
  timeEntryIds: string[];
  dueDate?: string;
  notes?: string;
}

export interface UpdateInvoiceInput {
  dueDate?: string | null;
  notes?: string | null;
  removeLineItemIds?: string[];
}

export type SeedSummary = {
  clients: number;
  time_entries: number;
  invoices: number;
};

export type FeedbackType = "bug" | "feature" | "ui" | "other";
export type FeedbackStatus =
  | "pending"
  | "acknowledged"
  | "clarification_requested"
  | "resolved";

export type FeedbackRow = {
  id: string;
  org_id: string | null;
  user_id: string | null;
  type: FeedbackType;
  subject: string;
  body: string;
  status: FeedbackStatus;
  admin_note: string | null;
  created_at: string;
  updated_at: string;
  submitter_email?: string | null;
  org_name?: string | null;
};

export type CreateFeedbackInput = {
  type: FeedbackType;
  subject: string;
  body: string;
};

export type UpdateFeedbackInput = {
  status?: FeedbackStatus;
  admin_note?: string | null;
};

export type ArScope = "global" | "per_client";

export type ArSettings = {
  automationEnabled: boolean;
  scope: ArScope;
  runDayOfMonth: number;
  approvalRequired: boolean;
  remindersEnabled: boolean;
  reminderCadenceDays: number;
};

export type UpdateArSettingsInput = Partial<ArSettings>;

export type ArPreviewDraft = {
  clientId: string;
  clientName: string;
  timeEntryCount: number;
  totalCents: number;
};

export type ArPreviewReminder = {
  invoiceId: string;
  invoiceNumber: string | null;
  clientName: string;
  daysPastIssue: number;
  reminderNumber: number;
};

export type ArPreview = {
  asOfDate: string;
  scheduledRunDate: string;
  wouldCreate: ArPreviewDraft[];
  wouldRemind: ArPreviewReminder[];
};

export type ArRunResult = {
  createdDrafts: string[];
  finalizedSent: string[];
  remindersSent: string[];
};
